matrix:
  include:
    - language: python
      python:
      - 2.7
      - 3.5
      before_install:
      - openssl aes-256-cbc -K $encrypted_f930a91c198a_key -iv $encrypted_f930a91c198a_iv
        -in packages/hbp-app-python-auth-master.zip.enc -out packages/hbp-app-python-auth-master.zip -d
      install:
      - sudo apt-get install libpq-dev python-dev
      - ls -R packages/
      - unzip packages/hbp-app-python-auth-master.zip -d packages/
      - pip install -f packages -r job_manager/requirements_ci.txt
      before_script:
      - export PYTHONPATH=$PYTHONPATH:$(pwd)
      - python -c "import django; print(django.get_version())"
      - export NMPI_ENV=travis
      script:
      - npm update -g npm
      - cd job_manager
      - python manage.py migrate --noinput
      - python manage.py test simqueue
    - language: node_js
      node_js:
      - "node"
      - "9"
      # before_script:
      before_install:
      - openssl aes-256-cbc -K $encrypted_b9b056d351f8_key -iv $encrypted_b9b056d351f8_iv -in job_manager/nmpi-job-manager-app/static_file_nmpi.zip.enc -out job_manager/nmpi-job-manager-app/static_file_nmpi.zip -d
      - export DISPLAY=:99.0
      - sh -e /etc/init.d/xvfb start
      script:
      # - cat job_manager/nmpi-job-manager-app/nmpi/karma.conf.js
      # - nvm ls
      # - karma --version
      # - ./node_modules/.bin/karma start job_manager/nmpi-job-manager-app/nmpi/karma.conf.js --browsers Chrome --single-run 
      - unzip job_manager/nmpi-job-manager-app/static_file_nmpi.zip 
      - find | grep -e "job_manager/nmpi-job-manager-app"
      - ./node_modules/.bin/karma start job_manager/nmpi-job-manager-app/nmpi/karma.conf.js --browsers PhantomJS --single-run 
      after_failure:
      - cat /home/travis/build/HumanBrainProject/hbp_neuromorphic_platform/npm-debug.log
