matrix:
  include:
    - language: python
      python:
      - 2.7
      - 3.5
      before_install:
      - openssl aes-256-cbc -K $encrypted_f930a91c198a_key -iv $encrypted_f930a91c198a_iv
        -in packages/hbp-app-python-auth-master.zip.enc -out packages/hbp-app-python-auth-master.zip -d
      install:
      - sudo apt-get install libpq-dev python-dev
      - ls -R packages/
      - unzip packages/hbp-app-python-auth-master.zip -d packages/
      - pip install -f packages -r job_manager/requirements_ci.txt
      before_script:
      - export PYTHONPATH=$PYTHONPATH:$(pwd)
      - python -c "import django; print(django.get_version())"
      - export NMPI_ENV=travis
      script:
      - npm update -g npm
      - cd job_manager
      - python manage.py migrate --noinput
      - python manage.py test simqueue
    - language: node_js
      node_js:
      - 0.8
      before_script:
      - export DISPLAY=:99.0
      - sh -e /etc/init.d/xvfb start
      stript:
      - cd job_manager/nmpi-job-manager-app/nmpi
      - node_modules/karma/bin/karma start --single-run
