name: Mirror to EBRAINS

on:
  push:
    branches: [ master, staging, api-v3 ]

jobs:
  to_ebrains:
    runs-on: ubuntu-latest
    steps:
      - name: syncmaster
        uses: wei/git-sync@v3
        with:
          source_repo: "HumanBrainProject/hbp_neuromorphic_platform"
          source_branch: "master"
          destination_repo: "https://ghpusher:${{ secrets.EBRAINS_GITLAB_ACCESS_TOKEN }}@gitlab.ebrains.eu/neuromorphic/job-queue-api.git"
          destination_branch: "main"
      - name: syncstaging
        uses: wei/git-sync@v3
        with:
          source_repo: "HumanBrainProject/hbp_neuromorphic_platform"
          source_branch: "staging"
          destination_repo: "https://ghpusher:${{ secrets.EBRAINS_GITLAB_ACCESS_TOKEN }}@gitlab.ebrains.eu/neuromorphic/job-queue-api.git"
          destination_branch: "staging"
      - name: sync-api-v3
        uses: wei/git-sync@v3
        with:
          source_repo: "HumanBrainProject/hbp_neuromorphic_platform"
          source_branch: "api-v3"
          destination_repo: "https://ghpusher:${{ secrets.EBRAINS_GITLAB_ACCESS_TOKEN }}@gitlab.ebrains.eu/neuromorphic/job-queue-api.git"
          destination_branch: "api-v3"
      - name: synctags
        uses: wei/git-sync@v3
        with:
          source_repo: "HumanBrainProject/hbp_neuromorphic_platform"
          source_branch: "refs/tags/*"
          destination_repo: "https://ghpusher:${{ secrets.EBRAINS_GITLAB_ACCESS_TOKEN }}@gitlab.ebrains.eu/neuromorphic/job-queue-api.git"
          destination_branch: "refs/tags/*"
